# Site settings
title: Varchar FTW
header-img: img/home-bg.png
email: brian.a.schoonmaker@gmail.com
copyright_name: brian-schoonmaker
description: >
  A rarely updated personal blog including thoughts based on my experience with backend and occasional brushes with frontend development.
baseurl: "" # the subpath of your site, e.g. /blog if we ever want to deal with multiple DNS entries
twitter_username:
github_username: brian-schoonmaker
linkedin_username: brian-a-schoonmaker
email_username: brian.a.schoonmaker@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

gems: [jekyll-paginate, jekyll-feed]
