# Site settings
title: Varchar FTW
header-img: img/home-bg.png
email: brian.a.schoonmaker@gmail.com
copyright_name: insomicman
description: > # this means to ignore newlines until "baseurl:"
  A primer on all things database, SQL and back-end development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  insomicman
learn_profile: insomicman
email_username: brian.a.schoonmaker@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
